### ISSUE TITLE
gmap api

### ISSUE THREAD

**Issue by madvincy** [IBM/predict-wildfire-intensity#12]
if i deploy on cloud how will i insert the api?

**Comment by scottdangelo** [comment]
Sorry, that part of the code needs fixing. For now, you can ssh to the instance and manually add your key to server/public/index.html to line#40:
```
        src="https://maps.googleapis.com/maps/api/js?key=<your_key_here>&callback=initMap"  >
```

I'll abstract that to the server/js/index.js file so that it can be added as an environment variable, but that change might not happen until monday.

**Comment by madvincy** [comment]
thanks

**Comment by scottdangelo** [comment]
This is now documented, and you can put the MAPS_APIKEY into the server/.env file to run locally, or update the IBM Cloud Deployment Runtime variable if running in the cloud.
